-- STATION V
-- Migration 001: initial PostgreSQL/PostGIS schema
-- M1 — Database foundation

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Catalogues
-- ============================================================

CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso2 VARCHAR(2) NOT NULL UNIQUE,
    iso3 VARCHAR(3) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    geometry GEOMETRY(MULTIPOLYGON, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT countries_iso2_uppercase
        CHECK (iso2 = upper(iso2)),
    CONSTRAINT countries_iso3_uppercase
        CHECK (iso3 = upper(iso3))
);

CREATE INDEX idx_countries_geometry
    ON countries USING GIST (geometry);

CREATE TABLE dimensions (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    weight NUMERIC(5,4) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT dimensions_weight_range
        CHECK (weight >= 0 AND weight <= 1)
);

CREATE TABLE subindicators (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id SMALLINT NOT NULL REFERENCES dimensions(id),
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    weight NUMERIC(6,4),
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT subindicators_weight_range
        CHECK (weight IS NULL OR (weight >= 0 AND weight <= 1))
);

CREATE INDEX idx_subindicators_dimension
    ON subindicators (dimension_id);

-- ============================================================
-- Source Registry / evidence model
-- ============================================================

CREATE TABLE sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    tier VARCHAR(2) NOT NULL,
    source_class VARCHAR(50) NOT NULL,
    source_type VARCHAR(80) NOT NULL,
    geographic_scope VARCHAR(30),
    coverage JSONB,
    reliability NUMERIC(5,2),
    roles JSONB,
    detection_capability NUMERIC(5,2),
    corroboration_capability NUMERIC(5,2),
    expertise JSONB,
    independence_group VARCHAR(100),
    access_method VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT sources_tier_valid
        CHECK (tier IN ('T0', 'T1', 'T2', 'T3', 'T4')),
    CONSTRAINT sources_reliability_range
        CHECK (reliability IS NULL OR (reliability >= 0 AND reliability <= 100)),
    CONSTRAINT sources_detection_range
        CHECK (detection_capability IS NULL OR (detection_capability >= 0 AND detection_capability <= 100)),
    CONSTRAINT sources_corroboration_range
        CHECK (corroboration_capability IS NULL OR (corroboration_capability >= 0 AND corroboration_capability <= 100))
);

CREATE INDEX idx_sources_tier ON sources (tier);
CREATE INDEX idx_sources_status ON sources (status);

CREATE TABLE evidence (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id UUID NOT NULL REFERENCES sources(id),
    published_at TIMESTAMPTZ,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    title TEXT,
    url TEXT,
    author TEXT,
    language VARCHAR(10),
    content_type VARCHAR(50),
    evidence_type VARCHAR(30) NOT NULL,
    source_role VARCHAR(30) NOT NULL,
    relationship_to_event VARCHAR(30),
    independence_group VARCHAR(100),
    evidence_quality NUMERIC(5,2),
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    content_hash VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT evidence_quality_range
        CHECK (evidence_quality IS NULL OR (evidence_quality >= 0 AND evidence_quality <= 100))
);

CREATE INDEX idx_evidence_source ON evidence (source_id);
CREATE INDEX idx_evidence_published_at ON evidence (published_at);
CREATE INDEX idx_evidence_content_hash ON evidence (content_hash);

CREATE TABLE claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evidence_id UUID NOT NULL REFERENCES evidence(id),
    claim_type VARCHAR(50) NOT NULL,
    statement TEXT NOT NULL,
    assertion_status VARCHAR(20) NOT NULL,
    confidence VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT claims_assertion_status_valid
        CHECK (assertion_status IN ('confirmed', 'reported', 'claimed', 'disputed', 'inferred'))
);

CREATE INDEX idx_claims_evidence ON claims (evidence_id);
CREATE INDEX idx_claims_type ON claims (claim_type);

CREATE TABLE evidence_relations (
    evidence_id UUID NOT NULL REFERENCES evidence(id) ON DELETE CASCADE,
    related_evidence_id UUID NOT NULL REFERENCES evidence(id) ON DELETE CASCADE,
    relation_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (evidence_id, related_evidence_id, relation_type),
    CONSTRAINT evidence_relations_not_self
        CHECK (evidence_id <> related_evidence_id)
);

CREATE INDEX idx_evidence_relations_related
    ON evidence_relations (related_evidence_id);

-- ============================================================
-- Events
-- ============================================================

CREATE TABLE events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    current_version_id UUID,
    duplicate_of UUID REFERENCES events(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    first_detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_evidence_at TIMESTAMPTZ
);

CREATE INDEX idx_events_duplicate_of ON events (duplicate_of);
CREATE INDEX idx_events_first_detected_at ON events (first_detected_at);

CREATE TABLE event_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    category VARCHAR(50) NOT NULL,
    subtype VARCHAR(80) NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    analyst_summary TEXT,
    location GEOGRAPHY(POINT, 4326),
    location_precision VARCHAR(30),
    region VARCHAR(150),
    place VARCHAR(255),
    time_start TIMESTAMPTZ,
    time_end TIMESTAMPTZ,
    time_precision VARCHAR(30),
    status VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    escalation_score NUMERIC(4,2),
    confidence VARCHAR(20) NOT NULL,
    confidence_score_internal NUMERIC(5,2),
    canonical_data JSONB,
    human_impact JSONB,
    material_impact JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT event_versions_unique_version
        UNIQUE (event_id, version),
    CONSTRAINT event_versions_severity_valid
        CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
    CONSTRAINT event_versions_escalation_valid
        CHECK (
            escalation_score IS NULL
            OR (
                severity IN ('high', 'critical')
                AND escalation_score >= 0
                AND escalation_score <= 10
            )
        ),
    CONSTRAINT event_versions_confidence_score_range
        CHECK (
            confidence_score_internal IS NULL
            OR (confidence_score_internal >= 0 AND confidence_score_internal <= 100)
        )
);

CREATE INDEX idx_event_versions_event ON event_versions (event_id);
CREATE INDEX idx_event_versions_severity ON event_versions (severity);
CREATE INDEX idx_event_versions_category ON event_versions (category);
CREATE INDEX idx_event_versions_status ON event_versions (status);
CREATE INDEX idx_event_versions_escalation ON event_versions (escalation_score DESC);
CREATE INDEX idx_event_versions_time_start ON event_versions (time_start);
CREATE INDEX idx_event_versions_location
    ON event_versions USING GIST (location);

ALTER TABLE events
    ADD CONSTRAINT events_current_version_fk
    FOREIGN KEY (current_version_id) REFERENCES event_versions(id);

CREATE TABLE event_countries (
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    country_id BIGINT NOT NULL REFERENCES countries(id),
    relationship_type VARCHAR(30) NOT NULL,

    PRIMARY KEY (event_id, country_id, relationship_type),
    CONSTRAINT event_countries_relationship_valid
        CHECK (relationship_type IN ('directly_affected', 'indirectly_affected'))
);

CREATE INDEX idx_event_countries_country
    ON event_countries (country_id);

CREATE TABLE actors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_actors_name ON actors (name);

CREATE TABLE event_actors (
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    actor_id UUID NOT NULL REFERENCES actors(id),
    role VARCHAR(50) NOT NULL,

    PRIMARY KEY (event_id, actor_id, role)
);

CREATE INDEX idx_event_actors_actor
    ON event_actors (actor_id);

CREATE TABLE event_relations (
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    related_event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    relation_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (event_id, related_event_id, relation_type),
    CONSTRAINT event_relations_not_self
        CHECK (event_id <> related_event_id)
);

CREATE INDEX idx_event_relations_related
    ON event_relations (related_event_id);

CREATE TABLE event_timeline (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL,
    update_type VARCHAR(50) NOT NULL,
    description TEXT,
    event_version_id UUID REFERENCES event_versions(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_event_timeline_event_timestamp
    ON event_timeline (event_id, timestamp DESC);

-- ============================================================
-- Risk model
-- ============================================================

CREATE TABLE risk_impacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id),
    country_id BIGINT NOT NULL REFERENCES countries(id),
    subindicator_id SMALLINT NOT NULL REFERENCES subindicators(id),
    base_impact NUMERIC(6,3) NOT NULL,
    relevance NUMERIC(6,3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT risk_impacts_base_range
        CHECK (base_impact >= 0 AND base_impact <= 100),
    CONSTRAINT risk_impacts_relevance_range
        CHECK (relevance >= 0 AND relevance <= 1)
);

CREATE INDEX idx_risk_impacts_event
    ON risk_impacts (event_id);
CREATE INDEX idx_risk_impacts_country
    ON risk_impacts (country_id);
CREATE INDEX idx_risk_impacts_subindicator
    ON risk_impacts (subindicator_id);

CREATE TABLE risk_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country_id BIGINT NOT NULL REFERENCES countries(id),
    timestamp TIMESTAMPTZ NOT NULL,
    internal_instability NUMERIC(5,2) NOT NULL,
    conflict_violence NUMERIC(5,2) NOT NULL,
    international_tension NUMERIC(5,2) NOT NULL,
    military_activity NUMERIC(5,2) NOT NULL,
    pressure_stress NUMERIC(5,2) NOT NULL,
    country_risk NUMERIC(5,2) NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    confidence_score_internal NUMERIC(5,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT risk_snapshots_internal_instability_range
        CHECK (internal_instability BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_conflict_violence_range
        CHECK (conflict_violence BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_international_tension_range
        CHECK (international_tension BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_military_activity_range
        CHECK (military_activity BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_pressure_stress_range
        CHECK (pressure_stress BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_country_risk_range
        CHECK (country_risk BETWEEN 0 AND 100),
    CONSTRAINT risk_snapshots_confidence_score_range
        CHECK (
            confidence_score_internal IS NULL
            OR (confidence_score_internal BETWEEN 0 AND 100)
        )
);

CREATE INDEX idx_risk_snapshots_country_timestamp
    ON risk_snapshots (country_id, timestamp DESC);

-- ============================================================
-- Seed methodology configuration
-- ============================================================

INSERT INTO dimensions (id, code, name, weight, description)
VALUES
    (1, 'internal_instability', 'Inestabilidad interna', 0.2500, 'Inestabilidad interna'),
    (2, 'conflict_violence', 'Conflicto y violencia', 0.2500, 'Conflicto y violencia'),
    (3, 'international_tension', 'Tensión internacional', 0.2000, 'Tensión internacional'),
    (4, 'military_activity', 'Actividad militar', 0.1500, 'Actividad militar'),
    (5, 'pressure_stress', 'Presión / estrés', 0.1500, 'Presión / estrés')
ON CONFLICT (id) DO NOTHING;

COMMIT;
